replicaCount: 1

image:
  repository: k8s-runtime-manager
  tag: "1.0"
  pullPolicy: Never

service:
  type: NodePort
  port: 8080
  nodePort: 30080

serviceAccount:
  create: true
  name: runtime-manager

namespace:
  managedWorkloads: default

resources: {}